#include "src/include.h"
#include "src/2hdmc.h"

#define USE_2HDMC

/*--------------------------------------------------------------------*/
/* Calculation of the observables, corresponding to a 2HDM point generated by 2HDMC */
/*--------------------------------------------------------------------*/

int main(int argc,char** argv)
{
	char name[50];
	double lambda1,lambda2,lambda3,lambda4,lambda5,lambda6,lambda7,m12_2,tanb,mA,delta0;
	double mh,mH,mHp,sba;
	int type,param;
	double obs[Nobs_BKsll+1];

	if(argc<4) 
	{ 
		printf(" This program needs 3 parameters:\n"
		"   type    Yukawa type (1-4)\n"
		"   tanb    tan(beta)\n"
		"   mA      CP-odd Higgs mass\n");
		printf(" Auxiliary parameters are:\n"
		"   parametrization: 1=generic with lambdas (default), 2=physical with Higgs masses  ()\n"
		"   If parametrization=1:\n"
		"      lambda1...7  Higgs potential parameters (by default MSSM like)\n"
		"      m12^2        if set, mA is not used (otherwise MSSM like)\n"                        
		"   If parametrization=2:\n"
		"      mh (default 125.03), mH (defaut=mA), mH+ (defaut=mA), sin(beta-alpha) (defaut 1), lambda6 (default 0), lambda7 (default 0), m12^2 (default MSSM-like) \n");                        
		exit(1); 
	} 
	else  
	{
		sscanf(argv[1],"%d",&type);
		sscanf(argv[2],"%lf",&tanb);
		sscanf(argv[3],"%lf",&mA);

		double g=6.51908e-1;
		double gp=3.57458e-1;

		if(argc>4) sscanf(argv[4],"%ld",&param); else param=1;   
		
		if(param==1)
		{
			if(argc>5) sscanf(argv[5],"%lf",&lambda1); else lambda1=(g*g+gp*gp)/4.;   
			if(argc>6) sscanf(argv[6],"%lf",&lambda2); else lambda2=lambda1;
			if(argc>7) sscanf(argv[7],"%lf",&lambda3); else lambda3=(g*g-gp*gp)/4.;
			if(argc>8) sscanf(argv[8],"%lf",&lambda4); else lambda4=-g*g/2.;
			if(argc>9) sscanf(argv[9],"%lf",&lambda5); else lambda5=0.;
			if(argc>10) sscanf(argv[10],"%lf",&lambda6); else lambda6=0.;
			if(argc>11) sscanf(argv[11],"%lf",&lambda7); else lambda7=0.;
			if(argc>12) sscanf(argv[12],"%lf",&m12_2); else m12_2=mA*mA*sin(2.*atan(tanb))/2.;
		}
		else if(param==2)
		{
			if(argc>5) sscanf(argv[5],"%lf",&mh); else mh=125.03;   
			if(argc>6) sscanf(argv[6],"%lf",&mH); else mH=mA;
			if(argc>7) sscanf(argv[7],"%lf",&mHp); else mHp=mA;
			if(argc>8) sscanf(argv[8],"%lf",&sba); else sba=1.;
			if(argc>9) sscanf(argv[9],"%lf",&lambda6); else lambda6=0.;
			if(argc>10) sscanf(argv[10],"%lf",&lambda7); else lambda7=0.;
			if(argc>11) sscanf(argv[11],"%lf",&m12_2); else m12_2=mA*mA*sin(2.*atan(tanb))/2.;
		}
		else
		{	
			printf("Wrong parametrization choice!\n");
			return 1;
		}
		
	}	
	sprintf(name,"thdm%d.lha",getpid());


	int filesOK=1;
#ifdef USE_2HDMC
	if(!test_file(THDMC)) 
	{
		printf("\"%s\" absent. Please check the 2HDMC path or comment \"#define USE_2HDMC\" in thdm.c\n",THDMC);
		filesOK=0;
	}
#endif
	if(!filesOK) return 1;


	if(!test_file("tmp")) system("mkdir tmp");
	chdir("tmp");
	
	printf("\n");
	
	printf("SuperIso " VERSION " - %d\n\n", YEAR);

#ifdef USE_2HDMC
	if(param==1) thdmc_types(lambda1,lambda2,lambda3,lambda4,lambda5,lambda6,lambda7,m12_2,tanb,type,name);
	else thdmc_phys(mh,mH,mA,mHp,sba,lambda6,lambda7,m12_2,tanb,type,name);
	
	printf("THDM - SLHA file generated by 2HDMC\n\n");

	delta0=delta0_calculator(name);
	if(delta0 !=0.)
	{
		printf("Observable\t\t\tValue\n\n");

		printf("BR(b->s gamma)\t\t\t%.3e\n",bsgamma_calculator(name));
		printf("delta0(B->K* gamma)\t\t%.3e\n\n",delta0);

		printf("BR(Bs->mu mu)\t\t\t%.3e\n",Bsmumu_calculator(name));
		printf("BR(Bs->mu mu)_untag\t\t%.3e\n",Bsmumu_untag_calculator(name));
		printf("BR(Bd->mu mu)\t\t\t%.3e\n\n",Bdmumu_calculator(name));
	
		printf("BR(B->K* mu mu)_low\t\t%.3e\n",BRobs_BKstarmumu_lowq2_calculator(name,obs));
		printf("AFB(B->K* mu mu)_low\t\t%.3e\n",obs[1]);
		printf("FL(B->K* mu mu)_low\t\t%.3e\n",obs[2]);
		printf("P1(B->K* mu mu)_low\t\t%.3e\n",obs[5]);
		printf("P2(B->K* mu mu)_low\t\t%.3e\n",obs[14]);
		printf("P4'(B->K* mu mu)_low\t\t%.3e\n",obs[17]);
		printf("P5'(B->K* mu mu)_low\t\t%.3e\n",obs[18]);
		printf("P6'(B->K* mu mu)_low\t\t%.3e\n",obs[19]);
		printf("P8'(B->K* mu mu)_low\t\t%.3e\n",obs[21]);
		printf("AI(B->K* mu mu)_low\t\t%.3e\n\n",AI_BKstarmumu_lowq2_calculator(name));
	
		printf("BR(B->K* mu mu)_high\t\t%.3e\n",BRobs_BKstarmumu_highq2_calculator(name,obs));
		printf("AFB(B->K* mu mu)_high\t\t%.3e\n",obs[1]);
		printf("FL(B->K* mu mu)_high\t\t%.3e\n",obs[2]);
		printf("P1(B->K* mu mu)_high\t\t%.3e\n",obs[5]);
		printf("P2(B->K* mu mu)_high\t\t%.3e\n",obs[14]);
		printf("P4'(B->K* mu mu)_high\t\t%.3e\n",obs[17]);
		printf("P5'(B->K* mu mu)_high\t\t%.3e\n",obs[18]);
		printf("P6'(B->K* mu mu)_high\t\t%.3e\n",obs[19]);
		printf("P8'(B->K* mu mu)_high\t\t%.3e\n",obs[21]);
		printf("AI(B->K* mu mu)_high\t\t%.3e\n\n",AI_BKstarmumu_highq2_calculator(name));

		
		printf("BR(B->Xs mu mu)_low\t\t%.3e\n",BRBXsmumu_lowq2_calculator(name));
		printf("BR(B->Xs mu mu)_high\t\t%.3e\n",BRBXsmumu_highq2_calculator(name));
		printf("q0^2(AFB(B->Xs mu mu)\t\t%.3e\n",A_BXsmumu_zero_calculator(name));
		printf("BR(B->Xs tau tau)_high\t\t%.3e\n\n",BRBXstautau_highq2_calculator(name));
	
		printf("BR(B->tau nu)\t\t\t%.3e\n",Btaunu_calculator(name));
		printf("R(B->tau nu)\t\t\t%.3e\n",RBtaunu_calculator(name));
		printf("BR(B->D tau nu)\t\t\t%.3e\n",BDtaunu_calculator(name));
		printf("BR(B->D tau nu)/BR(B->D e nu)\t%.3e\n",BDtaunu_BDenu_calculator(name));
		printf("BR(Ds->tau nu)\t\t\t%.3e\n",Dstaunu_calculator(name));
		printf("BR(Ds->mu nu)\t\t\t%.3e\n",Dsmunu_calculator(name));
		printf("BR(D->mu nu)\t\t\t%.3e\n",Dmunu_calculator(name));
		printf("BR(K->mu nu)/BR(pi->mu nu)\t%.3e\n",Kmunu_pimunu_calculator(name));
		printf("Rmu23(K->mu nu)\t\t\t%.3e\n\n",Rmu23_calculator(name));

		printf("a_muon\t\t\t\t%.3e\n\n",muon_gm2_calculator(name));
	}
	else printf("Invalid point\n\n");
#endif

	sprintf(name,"rm -f thdm%d.lha",getpid());
	system(name);
	return 1;
}
